/**
 * HTML Reporter for MCP-Jest
 *
 * Generates beautiful, interactive HTML test reports.
 */

import { promises as fs } from 'fs';
import { resolve, dirname } from 'path';
import type { TestSuite, TestResult } from './types.js';

/**
 * Reporter options
 */
export interface ReporterOptions {
  /** Output file path */
  outputPath?: string;
  /** Report title */
  title?: string;
  /** Include timestamp in filename */
  timestamp?: boolean;
  /** Open report in browser after generation */
  open?: boolean;
  /** Theme: light or dark */
  theme?: 'light' | 'dark' | 'auto';
  /** Include raw JSON data */
  includeRawData?: boolean;
}

/**
 * HTML Reporter
 *
 * Generates interactive HTML reports for test results
 */
export class HTMLReporter {
  private options: Required<ReporterOptions>;

  constructor(options: ReporterOptions = {}) {
    this.options = {
      outputPath: options.outputPath || './mcp-jest-report.html',
      title: options.title || 'MCP-Jest Test Report',
      timestamp: options.timestamp ?? true,
      open: options.open ?? false,
      theme: options.theme || 'auto',
      includeRawData: options.includeRawData ?? true
    };
  }

  /**
   * Generate HTML report from test results
   */
  async generate(suite: TestSuite, serverInfo?: { command: string; args?: string[] }): Promise<string> {
    const html = this.buildHTML(suite, serverInfo);

    // Determine output path
    let outputPath = this.options.outputPath;
    if (this.options.timestamp) {
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
      const ext = outputPath.endsWith('.html') ? '' : '.html';
      outputPath = outputPath.replace(/\.html$/, '') + `-${timestamp}${ext}`;
    }

    // Ensure directory exists
    await fs.mkdir(dirname(resolve(outputPath)), { recursive: true });

    // Write file
    await fs.writeFile(resolve(outputPath), html, 'utf-8');

    // Open in browser if requested
    if (this.options.open) {
      await this.openInBrowser(resolve(outputPath));
    }

    return resolve(outputPath);
  }

  /**
   * Build HTML content
   */
  private buildHTML(suite: TestSuite, serverInfo?: { command: string; args?: string[] }): string {
    const passRate = suite.total > 0 ? Math.round((suite.passed / suite.total) * 100) : 0;
    const statusClass = suite.failed === 0 ? 'success' : 'failure';

    // Group results by type
    const byType = this.groupResultsByType(suite.results);

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this.escapeHtml(this.options.title)}</title>
  <style>
    ${this.getStyles()}
  </style>
</head>
<body class="theme-${this.options.theme}">
  <div class="container">
    <header>
      <h1>🧪 ${this.escapeHtml(this.options.title)}</h1>
      <p class="timestamp">Generated: ${new Date().toLocaleString()}</p>
      ${serverInfo ? `<p class="server-info">Server: <code>${this.escapeHtml(serverInfo.command)} ${(serverInfo.args || []).join(' ')}</code></p>` : ''}
    </header>

    <section class="summary ${statusClass}">
      <div class="stat-grid">
        <div class="stat">
          <span class="stat-value">${suite.passed}</span>
          <span class="stat-label">Passed</span>
        </div>
        <div class="stat">
          <span class="stat-value">${suite.failed}</span>
          <span class="stat-label">Failed</span>
        </div>
        <div class="stat">
          <span class="stat-value">${suite.skipped}</span>
          <span class="stat-label">Skipped</span>
        </div>
        <div class="stat">
          <span class="stat-value">${suite.total}</span>
          <span class="stat-label">Total</span>
        </div>
      </div>

      <div class="progress-bar">
        <div class="progress-fill" style="width: ${passRate}%"></div>
      </div>
      <p class="pass-rate">${passRate}% Pass Rate • ${suite.duration}ms Duration</p>
    </section>

    <section class="results">
      ${Object.entries(byType).map(([type, results]) => this.buildTypeSection(type, results)).join('')}
    </section>

    ${this.options.includeRawData ? `
    <section class="raw-data">
      <h2>📄 Raw Data</h2>
      <details>
        <summary>View JSON</summary>
        <pre><code>${this.escapeHtml(JSON.stringify(suite, null, 2))}</code></pre>
      </details>
    </section>
    ` : ''}

    <footer>
      <p>Generated by <a href="https://npmjs.com/package/mcp-jest">mcp-jest</a></p>
    </footer>
  </div>

  <script>
    ${this.getScript()}
  </script>
</body>
</html>`;
  }

  /**
   * Group results by type
   */
  private groupResultsByType(results: TestResult[]): Record<string, TestResult[]> {
    return results.reduce((acc, result) => {
      if (!acc[result.type]) acc[result.type] = [];
      acc[result.type].push(result);
      return acc;
    }, {} as Record<string, TestResult[]>);
  }

  /**
   * Build section for a test type
   */
  private buildTypeSection(type: string, results: TestResult[]): string {
    const passed = results.filter(r => r.status === 'pass').length;
    const failed = results.filter(r => r.status === 'fail').length;
    const skipped = results.filter(r => r.status === 'skip').length;

    const typeIcons: Record<string, string> = {
      connection: '🔌',
      capability: '📋',
      tool: '🔧',
      resource: '📁',
      prompt: '💬'
    };

    return `
    <div class="type-section">
      <h2 class="type-header" onclick="toggleSection(this)">
        <span class="type-icon">${typeIcons[type] || '📦'}</span>
        <span class="type-name">${type.charAt(0).toUpperCase() + type.slice(1)} Tests</span>
        <span class="type-stats">
          <span class="badge pass">${passed}</span>
          <span class="badge fail">${failed}</span>
          ${skipped > 0 ? `<span class="badge skip">${skipped}</span>` : ''}
        </span>
        <span class="toggle-icon">▼</span>
      </h2>
      <div class="type-content">
        ${results.map(result => this.buildResultCard(result)).join('')}
      </div>
    </div>`;
  }

  /**
   * Build result card
   */
  private buildResultCard(result: TestResult): string {
    const statusIcons: Record<string, string> = {
      pass: '✅',
      fail: '❌',
      skip: '⏭️'
    };

    return `
    <div class="result-card ${result.status}">
      <div class="result-header">
        <span class="result-icon">${statusIcons[result.status]}</span>
        <span class="result-name">${this.escapeHtml(result.name)}</span>
        ${result.duration ? `<span class="result-duration">${result.duration}ms</span>` : ''}
      </div>
      ${result.message ? `<p class="result-message">${this.escapeHtml(result.message)}</p>` : ''}
      ${result.error ? `
        <details class="error-details">
          <summary>Error Details</summary>
          <pre>${this.escapeHtml(result.error.message)}</pre>
        </details>
      ` : ''}
    </div>`;
  }

  /**
   * Get CSS styles
   */
  private getStyles(): string {
    return `
    :root {
      --bg-primary: #ffffff;
      --bg-secondary: #f8f9fa;
      --text-primary: #212529;
      --text-secondary: #6c757d;
      --border-color: #dee2e6;
      --success-color: #28a745;
      --failure-color: #dc3545;
      --warning-color: #ffc107;
      --info-color: #17a2b8;
    }

    @media (prefers-color-scheme: dark) {
      .theme-auto {
        --bg-primary: #1a1a2e;
        --bg-secondary: #16213e;
        --text-primary: #e9ecef;
        --text-secondary: #adb5bd;
        --border-color: #2d3748;
      }
    }

    .theme-dark {
      --bg-primary: #1a1a2e;
      --bg-secondary: #16213e;
      --text-primary: #e9ecef;
      --text-secondary: #adb5bd;
      --border-color: #2d3748;
    }

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
      background: var(--bg-primary);
      color: var(--text-primary);
      line-height: 1.6;
    }

    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 2rem;
    }

    header {
      text-align: center;
      margin-bottom: 2rem;
    }

    header h1 {
      font-size: 2rem;
      margin-bottom: 0.5rem;
    }

    .timestamp, .server-info {
      color: var(--text-secondary);
      font-size: 0.9rem;
    }

    code {
      background: var(--bg-secondary);
      padding: 0.2em 0.4em;
      border-radius: 3px;
      font-family: 'Monaco', 'Menlo', monospace;
    }

    .summary {
      background: var(--bg-secondary);
      border-radius: 12px;
      padding: 2rem;
      margin-bottom: 2rem;
    }

    .summary.success {
      border-left: 4px solid var(--success-color);
    }

    .summary.failure {
      border-left: 4px solid var(--failure-color);
    }

    .stat-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 1rem;
      margin-bottom: 1.5rem;
    }

    .stat {
      text-align: center;
    }

    .stat-value {
      display: block;
      font-size: 2.5rem;
      font-weight: bold;
    }

    .stat-label {
      color: var(--text-secondary);
      font-size: 0.9rem;
      text-transform: uppercase;
    }

    .progress-bar {
      height: 8px;
      background: var(--border-color);
      border-radius: 4px;
      overflow: hidden;
      margin-bottom: 0.5rem;
    }

    .progress-fill {
      height: 100%;
      background: linear-gradient(90deg, var(--success-color), #20c997);
      transition: width 0.3s ease;
    }

    .pass-rate {
      text-align: center;
      color: var(--text-secondary);
    }

    .type-section {
      background: var(--bg-secondary);
      border-radius: 8px;
      margin-bottom: 1rem;
      overflow: hidden;
    }

    .type-header {
      display: flex;
      align-items: center;
      padding: 1rem 1.5rem;
      cursor: pointer;
      user-select: none;
    }

    .type-header:hover {
      background: var(--border-color);
    }

    .type-icon {
      margin-right: 0.75rem;
      font-size: 1.25rem;
    }

    .type-name {
      flex: 1;
      font-weight: 600;
    }

    .type-stats {
      display: flex;
      gap: 0.5rem;
      margin-right: 1rem;
    }

    .badge {
      padding: 0.25rem 0.5rem;
      border-radius: 12px;
      font-size: 0.75rem;
      font-weight: bold;
    }

    .badge.pass { background: var(--success-color); color: white; }
    .badge.fail { background: var(--failure-color); color: white; }
    .badge.skip { background: var(--warning-color); color: black; }

    .toggle-icon {
      transition: transform 0.2s;
    }

    .type-section.collapsed .toggle-icon {
      transform: rotate(-90deg);
    }

    .type-section.collapsed .type-content {
      display: none;
    }

    .type-content {
      padding: 0 1.5rem 1rem;
    }

    .result-card {
      background: var(--bg-primary);
      border-radius: 6px;
      padding: 1rem;
      margin-bottom: 0.75rem;
      border-left: 3px solid transparent;
    }

    .result-card.pass { border-left-color: var(--success-color); }
    .result-card.fail { border-left-color: var(--failure-color); }
    .result-card.skip { border-left-color: var(--warning-color); }

    .result-header {
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }

    .result-icon {
      font-size: 1rem;
    }

    .result-name {
      flex: 1;
      font-weight: 500;
    }

    .result-duration {
      color: var(--text-secondary);
      font-size: 0.85rem;
    }

    .result-message {
      margin-top: 0.5rem;
      color: var(--text-secondary);
      font-size: 0.9rem;
    }

    .error-details {
      margin-top: 0.5rem;
    }

    .error-details pre {
      background: var(--bg-secondary);
      padding: 1rem;
      border-radius: 4px;
      overflow-x: auto;
      font-size: 0.85rem;
      margin-top: 0.5rem;
    }

    .raw-data {
      margin-top: 2rem;
    }

    .raw-data h2 {
      margin-bottom: 1rem;
    }

    .raw-data pre {
      background: var(--bg-secondary);
      padding: 1rem;
      border-radius: 8px;
      overflow-x: auto;
      font-size: 0.8rem;
    }

    footer {
      text-align: center;
      margin-top: 3rem;
      padding-top: 2rem;
      border-top: 1px solid var(--border-color);
      color: var(--text-secondary);
    }

    footer a {
      color: var(--info-color);
      text-decoration: none;
    }

    @media (max-width: 768px) {
      .stat-grid {
        grid-template-columns: repeat(2, 1fr);
      }
    }
    `;
  }

  /**
   * Get JavaScript for interactivity
   */
  private getScript(): string {
    return `
    function toggleSection(header) {
      const section = header.closest('.type-section');
      section.classList.toggle('collapsed');
    }

    // Expand failed sections by default
    document.querySelectorAll('.result-card.fail').forEach(card => {
      const section = card.closest('.type-section');
      section.classList.remove('collapsed');
    });

    // Collapse passing sections by default
    document.querySelectorAll('.type-section').forEach(section => {
      const hasFailed = section.querySelector('.result-card.fail');
      if (!hasFailed) {
        section.classList.add('collapsed');
      }
    });
    `;
  }

  /**
   * Escape HTML special characters
   */
  private escapeHtml(text: string): string {
    const map: Record<string, string> = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#039;'
    };
    return text.replace(/[&<>"']/g, char => map[char]);
  }

  /**
   * Open file in browser
   */
  private async openInBrowser(filePath: string): Promise<void> {
    const { platform } = process;
    const { exec } = await import('child_process');

    const command = platform === 'darwin'
      ? `open "${filePath}"`
      : platform === 'win32'
        ? `start "" "${filePath}"`
        : `xdg-open "${filePath}"`;

    exec(command);
  }
}

/**
 * Generate HTML report (convenience function)
 */
export async function generateHTMLReport(
  suite: TestSuite,
  options?: ReporterOptions,
  serverInfo?: { command: string; args?: string[] }
): Promise<string> {
  const reporter = new HTMLReporter(options);
  return reporter.generate(suite, serverInfo);
}
